version: "3"

services:
  mysql:
    image: mysql:5.7
    container_name: venda_de_ingresso
    restart: always
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: venda-de-ingresso
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306

  mysql_test:
    image: mysql:5.7
    container_name: venda_de_ingresso_test
    restart: always
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: venda-de-ingresso-test
      MYSQL_PASSWORD: root
    ports:
      - 3307:3306

